### ISSUE TITLE
add greeting text

### ISSUE THREAD

**Issue by usertam** [usertam/library#6]
We should print some greeting text when the program is started, so the users will know what to do. 

Something like: 
`Welcome to the library system!`
`Enter 'help' for a list of built-in commands.`

**Comment by nehalimbu** [comment]
is this similar to menu? or is is to just show the built-in commands, and nothing else?
+ do we have a menu? I think I saw you had one but i cant find it.

**Comment by usertam** [comment]
No it just shows the command list and do nothing else. And we don't have a menu.

**Comment by nehalimbu** [comment]
so like user 2 commands? and then you can log in and see more?

**Comment by usertam** [comment]
Oh shoot I was thinking about the help command in the previous comment. Here we just do the greetings text.

**Comment by usertam** [comment]
Implemented in commit 8da5977.
